'use strict';
window.ProjectProcess=(()=>{
  const selected={poker:1,indie:1};
  const labels=[['Design','設計'],['AI generation','AI 生成'],['Frontend implementation','前端實現'],['Debugging','調試'],['Launch','上線']];
  const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
  const steps={
    poker:[
      {title:['Make the rules feel simple.','讓規則變得直覺。'],copy:['Define the core loop: place cards, complete a line, form a poker hand and understand the score.','定義核心循環：放置卡牌、完成一行、組成牌型，再理解計分。'],image:'pokericabra-2.jpg',caption:['Hand reference · Released app','牌型參考 · 已發佈應用程式'],facts:[['Game loop','遊戲循環'],['Touch interactions','觸控互動'],['Scoring hierarchy','計分層級']]},
      {title:['An AI-generated idea you can play.','AI 生成，親手試玩。'],copy:['This supplied HTML5 prototype turns the game interaction into a working, playable experience. Try it here.','這份 AI 生成的 HTML5 原型，把遊戲互動轉化為可運行的體驗。直接在此試玩。'],image:'pokericabra-prototype.png',caption:['AI-generated playable prototype · Original HTML','AI 生成的可玩原型 · 原始 HTML'],facts:[['AI-generated HTML','AI 生成 HTML'],['Playable interaction','可玩互動'],['One self-contained file','單一獨立檔案']],prototype:true},
      {title:['The interface is executable code.','介面，化為可運行程式碼。'],copy:['Canvas rendering, JavaScript game rules and touch input run together in the browser. The core interaction is shown below.','Canvas 繪圖、JavaScript 遊戲規則與觸控輸入，在瀏覽器中共同運行。下方展示核心互動程式。'],code:true,facts:[['HTML5 Canvas','HTML5 Canvas'],['JavaScript rules','JavaScript 規則'],['Touch input','觸控輸入']]},
      {title:['Refine the details that players feel.','調試玩家感受到的每個細節。'],copy:['Iterate on tutorial focus, scoring feedback and Chinese labels so that every action has an understandable result.','反覆改善教學焦點、計分回饋及中文標籤，讓每次操作都有清楚結果。'],image:'pokericabra-battle.jpg',caption:['Scoring feedback · Released app','計分回饋 · 已發佈應用程式'],facts:[['Tutorial refinement','教學修訂'],['Readable battle log','易讀戰鬥紀錄'],['Chinese localization','中文本地化']]},
      {title:['A complete product. On Google Play.','完整產品，已上架 Google Play。'],copy:['Deliver the Android product with its gameplay, progression, cloud save, billing and rewards.','交付 Android 產品，整合玩法、進度、雲端存檔、付款及獎勵。'],image:'pokericabra-1.jpg',caption:['Pokericabra Trainee · Public release','Pokericabra Trainee · 已公開發佈'],facts:[['Android integration','Android 整合'],['Release delivery','版本交付'],['Publicly available','已公開發佈']],release:true}
    ],
    indie:[
      {title:['Give a complex product a clear structure.','為複雜產品建立清晰結構。'],copy:['Organize creation into Idea, Presentation and Release, with a shared planning and production timeline.','把建立專案分為構思、呈現及發佈，並共用策劃與製作時間軸。'],image:'indie-project.png',caption:['Project creation · Design concept','建立專案 · 設計概念'],facts:[['Information architecture','資訊架構'],['Grouped decisions','分組決策'],['Project workflow','專案流程']]},
      {title:['Explore the product before building it.','先探索體驗，再推進實作。'],copy:['Use ImageGen to explore layouts and icons, critique the result, then refine the chosen direction before implementation.','以 ImageGen 探索佈局與圖示，覆核結果，修訂所選方向後再實作。'],image:'iteration/genre-ai.png',caption:['AI-assisted UI concept · Not a runtime screenshot','AI 協作 UI 概念 · 非實際運行截圖'],facts:[['Visual exploration','視覺探索'],['UI concepts','UI 概念'],['Review & iteration','覆核及迭代']]},
      {title:['From a screen concept to a working interface.','從畫面概念，到可運行介面。'],copy:['Turn the chosen design into a working screen, with grouped settings, clear illustrated options and a shared schedule.','把選定設計做成可操作的畫面，整合分組設定、清晰圖像選項及共用時間安排。'],image:'iteration/creation-current.png',caption:['Working interface · 13 Sep 2026','實際介面 · 2026 年 9 月 13 日'],facts:[['Working interface','可運行介面'],['Connected product data','連接產品數據'],['Working build','可運行版本']],native:true},
      {title:['Build. Check. Refine.','實作、檢查、再改善。'],copy:['Check real interface states and test the app. Version Alpha records 58 checks each for the demo and full versions.','檢查實際介面狀態，並測試應用程式。初版紀錄中，試玩及完整版本各通過 58 項檢查。'],checks:true,facts:[['Packaged verification','封裝驗證'],['Separate saves','獨立存檔'],['Recorded build evidence','已記錄版本證據']]},
      {title:['Working builds. Public launch ahead.','已有可運行版本，準備走向公開發佈。'],copy:['Version Alpha is already running. Interface improvements continue, with unfinished features clearly labelled. Public launch is pending.','初版已可運行。介面持續改善，未完成的功能清楚標示；尚待公開上線。'],image:'iteration/ideas-current.png',caption:['Working tools menu · Some features pending','實際工具選單 · 部分功能待完成'],facts:[['Native UI','原生介面'],['Ongoing development','持續開發'],['Launch pending','待公開上線']],pending:true}
    ]
  };
  function teaser(indie){const key=indie?'indie':'poker';return `<div class="process-teaser" role="group" aria-label="${t('Explore the complete product workflow','探索完整產品流程')}">${labels.map((label,i)=>`<button type="button" data-process-jump="${i}" data-process-key="${key}" aria-controls="build-process">${t(...label)}</button>${i<4?arrow:''}`).join('')}</div>`;}
  function poster(){return `<img src="assets/pokericabra-prototype.png" alt="${t('Playable AI-generated Pokericabra prototype','AI 生成的 Pokericabra 可玩原型')}" width="360" height="575">`;}
  function media(s,indie){
    if(s.prototype)return `<figure class="process-prototype"><div class="prototype-host" data-prototype-host>${poster()}</div><figcaption>${t(...s.caption)}</figcaption></figure>`;
    if(s.code)return `<div class="process-code"><div class="code-file">Pokericabra.html <span>HTML5 · JavaScript</span></div><pre aria-label="${t('Excerpt from the supplied HTML prototype','提供的 HTML 原型程式碼節錄')}"><code>&lt;canvas id="game"&gt;&lt;/canvas&gt;

function begin() {
  show($('overScreen'), false);
  game.start();
}

$('btnRetry').addEventListener('click', begin);</code></pre><p>${t('Canvas element, game start and retry · excerpts from the supplied source','Canvas 元素、遊戲啟動及重試 · 提供原始碼的節錄')}</p><div class="code-capabilities"><span>Canvas</span>${arrow}<span>${t('Game rules','遊戲規則')}</span>${arrow}<span>${t('Touch','觸控')}</span></div></div>`;
    if(s.checks)return `<div class="process-checks"><h4>${t('Version Alpha · Test results','初版 · 測試結果')}</h4><p><time datetime="2026-09-12">${t('12 September 2026','2026 年 9 月 12 日')}</time></p><dl>${['Demo','Full'].map(name=>`<div><dt>${name}</dt><dd><strong>58</strong> ${t('passed','通過')}<span>0 ${t('failures','失敗')}</span></dd></div>`).join('')}</dl><small>${t('Recorded checkpoint, not a new test run. Public release pending.','已記錄的檢查結果，並非本次重新測試。尚待公開上線。')}</small></div>`;
    return `<figure class="process-image ${indie?'landscape':'portrait'}"><button type="button" class="image-button" data-image="${s.image}" data-caption="${t(...s.caption)}"><img src="assets/${s.image}" alt="${t(...s.caption)}" loading="lazy"></button><figcaption>${t(...s.caption)}</figcaption></figure>`;
  }
  function render(indie){const key=indie?'indie':'poker',active=selected[key],s=steps[key][active];return `<section class="build-process" id="build-process" data-process-key="${key}"><header><h2>${t('From design to launch.','從設計，到上線。')}</h2><p>${indie?t('One continuous workflow. Public launch is the next milestone.','一套持續推進的流程，公開上線是下一個里程碑。'):t('One complete workflow. A playable AI prototype. A released app.','一套完整流程，可玩的 AI 原型，已發佈的應用程式。')}</p></header><div class="process-stages" role="tablist" aria-label="${t('Five stages of product delivery','產品交付的五個階段')}">${labels.map((label,i)=>`<button type="button" role="tab" id="stage-${i}" data-process-stage="${i}" aria-controls="process-panel" aria-selected="${active===i}" tabindex="${active===i?0:-1}"><span class="stage-number">${String(i+1).padStart(2,'0')}</span><strong>${t(...label)}</strong><small>${indie&&i===4?t('Pending','待上線'):indie&&i===3?t('Verified build','版本已驗證'):i===4?t('Released','已發佈'):t('View evidence','查看實例')}</small>${i<4?arrow:''}</button>`).join('')}</div><div class="process-panel" id="process-panel" role="tabpanel" aria-labelledby="stage-${active}"><div class="process-copy"><h3>${t(...s.title)}</h3><p>${t(...s.copy)}</p><ul>${s.facts.map(f=>`<li>${t(...f)}</li>`).join('')}</ul>${s.prototype?`<div class="prototype-actions"><button type="button" class="primary-button" data-prototype-toggle aria-pressed="false">${t('Play AI prototype','試玩 AI 原型')}${arrow}</button></div><p class="prototype-instructions">${t('Tap to rotate. Drag to move. Swipe down to drop. Prototype controls remain in English.','點按旋轉，拖曳移動，向下滑動落牌。原型操作文字保留英文。')}</p>`:''}${s.release?`<a class="process-store" href="https://play.google.com/store/apps/details?id=com.pokericabra.trainee" target="_blank" rel="noopener"><img src="assets/google-play-badge.png" width="180" height="70" alt="Get it on Google Play"></a>`:''}${s.native?`<p class="process-note">${t('Native frontend, built in Godot.','以 Godot 實作的原生前端。')}</p>`:''}${s.pending?`<span class="process-pending">${t('In development · Launch pending','開發中 · 待公開上線')}</span>`:''}<button type="button" class="process-next" data-process-stage="${(active+1)%5}">${active===4?t('Back to design','回到設計'):t('Next: ','下一步：')+t(...labels[active+1])}${arrow}</button></div>${media(s,indie)}</div></section>`;}
  function mount(root){root.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;const jump=button.dataset.processJump,index=button.dataset.processStage;if(jump!==undefined||index!==undefined){const section=root.querySelector('.build-process');if(!section)return;const key=section.dataset.processKey;selected[key]=Number(jump??index);section.outerHTML=render(key==='indie');const next=root.querySelector('.build-process');if(jump!==undefined)next.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});next.querySelector(`[data-process-stage="${selected[key]}"]`).focus({preventScroll:true});}if(button.hasAttribute('data-prototype-toggle')){const host=root.querySelector('[data-prototype-host]'),running=button.getAttribute('aria-pressed')==='true';host.innerHTML=running?poster():`<iframe src="prototypes/Pokericabra.html" title="${t('Playable Pokericabra AI prototype','可玩的 Pokericabra AI 原型')}" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer"></iframe>`;button.setAttribute('aria-pressed',String(!running));button.innerHTML=(running?t('Play AI prototype','試玩 AI 原型'):t('Stop prototype','停止原型'))+arrow;}});root.addEventListener('keydown',e=>{if(!e.target.matches('.process-stages [data-process-stage]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=Number(e.target.dataset.processStage),next=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowRight'?1:4))%5;root.querySelector(`.process-stages [data-process-stage="${next}"]`).click();});}
  return{render,teaser,mount};
})();
